apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyc-taxi-demand-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyc-taxi-demand-api
  template:
    metadata:
      labels:
        app: nyc-taxi-demand-api
    spec:
      containers:
        - name: api
          image: nyc-taxi-demand-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20