apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

images:
  - name: nyc-taxi-demand-api
    newName: ghcr.io/daya-alexandra/nyc-taxi-demand-mlops
    newTag: latest