apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nyc-taxi-demand-mlops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_WITH_OWNER/nyc-taxi-demand-mlops.git
    targetRevision: main
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nyc-taxi-demand
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
